export const GARAGE = [
  {
    name: 'Abider',
    type: 'Civilian',
    fuelCapacity: 49,
    efficiency: 3.28,
    imgUrl: '/img/garageIMG/abider.png',
  },
  {
    name: 'Afterburn',
    type: 'Civilian',
    fuelCapacity: 16,
    efficiency: 3.16,
    imgUrl: '/img/garageIMG/afterburn.png',
  },
  {
    name: 'Boson',
    type: 'Electric',
    battery: 16,
    batteryCharge: 2.16,
    imgUrl: '/img/garageIMG/boson.png',
  },
  {
    name: 'Exstatic',
    type: 'Electric',
    battery: 16,
    batteryCharge: 2.16,
    imgUrl: '/img/garageIMG/exstatic.png',
  },
  {
    name: 'Blaze',
    type: 'Civilian',
    fuelCapacity: 46.5,
    efficiency: 1.8,
    imgUrl: '/img/garageIMG/blaze.png',
  },
  {
    name: 'GX Spider',
    type: 'Civilian',
    fuelCapacity: 18,
    efficiency: 3.16,
    imgUrl: '/img/garageIMG/gxspider.png',
  },
  {
    name: 'Flare',
    type: 'Electric',
    battery: 16,
    batteryCharge: 1.16,

    imgUrl: '/img/garageIMG/flare.png',
  },
  {
    name: 'Landscape',
    type: 'Civilian',
    fuelCapacity: 46.5,
    efficiency: 3,
    imgUrl: '/img/garageIMG/landscape.png',
  },
  {
    name: 'Path Watcher',
    type: 'Civilian',
    fuelCapacity: 49,
    efficiency: 2.78,
    imgUrl: '/img/garageIMG/pathwatcher.png',
  },
  {
    name: 'Scenery',
    type: 'Civilian',
    fuelCapacity: 46.5,
    efficiency: 2.8,
    imgUrl: '/img/garageIMG/scenery.png',
  },
  {
    name: 'VectorBlade',
    type: 'Electric',
    fuelCapacity: 12,
    efficiency: 2,
    imgUrl: '/img/garageIMG/vectorblade.png',
  },
  {
    name: 'Road CM',
    type: 'Motorbike',
    battery: 18,
    batteryCharge: 2.5,
    imgUrl: '/img/garageIMG/roadcm.png',
  },
  {
    name: 'Firespin',
    type: 'Electric',
    battery: 18,
    batteryCharge: 2.5,
    imgUrl: '/img/garageIMG/firespin.png',
  },
  {
    name: 'Terminator Motorbike',
    type: 'Motorbike',
    fuelCapacity: 12,
    efficiency: 2,
    imgUrl: '/img/garageIMG/terminatorMotorbike.png',
  },
  {
    name: 'IC-8 Incursion',
    type: 'Tank',
    fuelCapacity: 33,
    efficiency: 4,
    imgUrl: '/img/garageIMG/ic-8Incursion.png',
  },
  {
    name: 'LC-4 Coercion',
    fuelCapacity: 50,
    efficiency: 3,
    type: 'Heavy',
    imgUrl: '/img/garageIMG/lc-4Coercion.png',
  },
  {
    name: 'MC-1 Restraint',
    type: 'Heavy',
    fuelCapacity: 40,
    efficiency: 3,
    imgUrl: '/img/garageIMG/mc-1Restraint.png',
  },
  {
    name: 'Exoshell',
    type: 'Heavy',
    fuelCapacity: 40,
    efficiency: 3.8,
    imgUrl: '/img/garageIMG/exoshell.png',
  },
  {
    name: 'MC-2 Pressure',
    type: 'Heavy',
    fuelCapacity: 40,
    efficiency: 2.8,
    imgUrl: '/img/garageIMG/mc-2Pressure.png',
  },
  {
    name: 'Path Keeper',
    type: 'Military',
    fuelCapacity: 30,
    efficiency: 2.8,
    imgUrl: '/img/garageIMG/pathkeeper.png',
  },
  {
    name: 'CV-1 Desert',
    type: 'Military',
    fuelCapacity: 27,
    efficiency: 2,
    imgUrl: '/img/garageIMG/cv-1Desert.png',
  },
  {
    name: 'RT-5 Shepherd',
    type: 'Heavy',
    fuelCapacity: 40,
    efficiency: 3.8,
    imgUrl: '/img/garageIMG/rt-5Shepard.png',
  },
  {
    name: 'Starfield X4',
    type: 'Heavy',
    fuelCapacity: 38,
    efficiency: 2.2,
    imgUrl: '/img/garageIMG/starfieldx4.png',
  },
  {
    name: 'Resistance Car',
    type: 'Military',
    fuelCapacity: 12,
    efficiency: 2,
    imgUrl: '/img/garageIMG/resistance.png',
  },
  {
    name: 'Warden',
    type: 'Heavy',
    fuelCapacity: 38,
    efficiency: 2,
    imgUrl: '/img/garageIMG/warden.png',
  },
  {
    name: 'Trail EX',
    type: 'Electric',
    battery: 18,
    batteryCharge: 2.5,
    imgUrl: '/img/garageIMG/trailex.png',
  },
  {
    name: 'Trail TX',
    type: 'Motorbike',
    fuelCapacity: 12,
    efficiency: 2,
    imgUrl: '/img/garageIMG/trailtx.png',
  },
  {
    name: 'Deinos',
    timer: 600,
    type: 'Aircraft',
    imgUrl: '/img/garageIMG/deinos.png',
  },
  {
    name: 'Gyps',
    timer: 720,
    type: 'Aircraft',
    imgUrl: '/img/garageIMG/gyps.png',
  },
  {
    name: 'Opheis',
    timer: 680,
    type: 'Aircraft',
    imgUrl: '/img/garageIMG/opheis.png',
  },
  {
    name: 'Overseer',
    timer: 900,
    type: 'Aircraft',
    imgUrl: '/img/garageIMG/oversteer.png',
  },
  {
    name: 'Blacklist helicopter',
    timer: 790,
    type: 'Aircraft',
    imgUrl: '/img/garageIMG/blacklist.png',
  },
];
